on:
  push:
    branches:
      - hashish


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'test github actions '
        run: pwd

      - name: 'printing '
        run: echo hashish